export interface Partner {
  id: string;
  name: string;
  email?: string;
  mobile?: string;
  imageUrl?: string;
  status: "verified" | "premium" | "kyc";
}

export const partners: Partner[] = [
  // Verified partners
  {
    id: "#1284",
    name: "Rajesh Kumar",
    email: "rajesh123@gmail.com",
    mobile: "9892412537",
    status: "verified",
    imageUrl: "userw.png",
  },
  {
    id: "#1285",
    name: "Priya Mehta",
    email: "priya.mehta@gmail.com",
    mobile: "9988776655",
    status: "verified",
    imageUrl: "userw.png",
  },
  {
    id: "#1286",
    name: "Vikas Sharma",
    email: "vikas.sharma@gmail.com",
    mobile: "9876543210",
    status: "verified",
    imageUrl: "userw.png",
  },
  {
    id: "#1287",
    name: "Nisha Rai",
    email: "nisha.rai@gmail.com",
    mobile: "9874512365",
    status: "verified",
    imageUrl: "userw.png",
  },
  {
    id: "#1288",
    name: "Ravi Patel",
    email: "ravi.patel@gmail.com",
    mobile: "9988771234",
    status: "verified",
    imageUrl: "userw.png",
  },
  {
    id: "#1289",
    name: "Kavita Desai",
    email: "kavita.desai@gmail.com",
    mobile: "9981234567",
    status: "verified",
    imageUrl: "userw.png",
  },
  {
    id: "#1290",
    name: "Amit Sinha",
    email: "amit.sinha@gmail.com",
    mobile: "9876543321",
    status: "verified",
    imageUrl: "userw.png",
  },
  {
    id: "#1291",
    name: "Neha Sharma",
    email: "neha.sharma@gmail.com",
    mobile: "9832176543",
    status: "verified",
    imageUrl: "userw.png",
  },
  {
    id: "#1292",
    name: "Rahul Chauhan",
    email: "rahul.chauhan@gmail.com",
    mobile: "9798012345",
    status: "verified",
    imageUrl: "userw.png",
  },
  {
    id: "#1293",
    name: "Arpita Reddy",
    email: "arpita.reddy@gmail.com",
    mobile: "9845012345",
    status: "verified",
    imageUrl: "userw.png",
  },
  {
    id: "#1294",
    name: "Sahil Verma",
    email: "sahil.verma@gmail.com",
    mobile: "9988776656",
    status: "verified",
    imageUrl: "userw.png",
  },
  {
    id: "#1295",
    name: "Swati Jain",
    email: "swati.jain@gmail.com",
    mobile: "9865432189",
    status: "verified",
    imageUrl: "userw.png",
  },

  // Premium partners
  {
    id: "#1296",
    name: "Anita Verma",
    email: "anita456@gmail.com",
    mobile: "8765432100",
    status: "premium",
    imageUrl: "userw.png",
  },
  {
    id: "#1297",
    name: "Manish Yadav",
    email: "manish.yadav@gmail.com",
    mobile: "9638527410",
    status: "premium",
    imageUrl: "userw.png",
  },
  {
    id: "#1298",
    name: "Rohini Kapoor",
    email: "rohini.kapoor@gmail.com",
    mobile: "9785632147",
    status: "premium",
    imageUrl: "userw.png",
  },
  {
    id: "#1299",
    name: "Sanjay Gupta",
    email: "sanjay.gupta@gmail.com",
    mobile: "9123456789",
    status: "premium",
    imageUrl: "userw.png",
  },
  {
    id: "#1300",
    name: "Deepak Mishra",
    email: "deepak.mishra@gmail.com",
    mobile: "9821045678",
    status: "premium",
    imageUrl: "userw.png",
  },
  {
    id: "#1301",
    name: "Ritika Sharma",
    email: "ritika.sharma@gmail.com",
    mobile: "9765432187",
    status: "premium",
    imageUrl: "userw.png",
  },
  {
    id: "#1302",
    name: "Mohit Agarwal",
    email: "mohit.agarwal@gmail.com",
    mobile: "9887654321",
    status: "premium",
    imageUrl: "userw.png",
  },
  {
    id: "#1303",
    name: "Sneha Saxena",
    email: "sneha.saxena@gmail.com",
    mobile: "9765431298",
    status: "premium",
    imageUrl: "userw.png",
  },
  {
    id: "#1304",
    name: "Pooja Nair",
    email: "pooja.nair@gmail.com",
    mobile: "9854123789",
    status: "premium",
    imageUrl: "userw.png",
  },
  {
    id: "#1305",
    name: "Shivani Sharma",
    email: "shivani.sharma@gmail.com",
    mobile: "9845671234",
    status: "premium",
    imageUrl: "userw.png",
  },
  {
    id: "#1306",
    name: "Abhishek Bhatia",
    email: "abhishek.bhatia@gmail.com",
    mobile: "9721034567",
    status: "premium",
    imageUrl: "userw.png",
  },

  // KYC partners
  {
    id: "#1307",
    name: "Suresh Gupta",
    email: "suresh.gupta@gmail.com",
    mobile: "9876543210",
    status: "kyc",
    imageUrl: "userw.png",
  },
  {
    id: "#1308",
    name: "Arjun Singh",
    email: "arjun.singh@gmail.com",
    mobile: "9876543211",
    status: "kyc",
    imageUrl: "userw.png",
  },
  {
    id: "#1309",
    name: "Sunita Joshi",
    email: "sunita.joshi@gmail.com",
    mobile: "9000000003",
    status: "kyc",
    imageUrl: "userw.png",
  },
  {
    id: "#1310",
    name: "Kiran Malhotra",
    email: "kiran.malhotra@gmail.com",
    mobile: "9000000004",
    status: "kyc",
    imageUrl: "userw.png",
  },
];
